export const formConfig = {
  leads: {
    title: "Lead",
    endpoint: "/api/leads",
    filterKey: "status",
    filter: ["Completed", "Confirmed", "Pending", "Dropped"],

    fields: [
      {
        name: "first_name",
        label: "First Name",
        type: "text",
        placeholder: "Enter first name",
        required: true,
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "last_name",
        label: "Last Name",
        type: "text",
        placeholder: "Enter last name",
        required: true,
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        placeholder: "Enter email",
        required: true,
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "phone",
        label: "Phone",
        type: "tel",
        placeholder: "Enter phone number",
        required: true,
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "source",
        label: "Source",
        type: "select",
        defaultValue: "",
        colSpan: 6,
        options: [
          "Website",
          "Cold Call",
          "Google Ads",
          "Instagram Ads",
          "LinkedIn",
          "Referral",
        ],
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        defaultValue: "Pending",
        colSpan: 6,
        options: ["Completed", "Confirmed", "Pending", "Dropped"],
      },
      {
        name: "dealValue",
        label: "Deal Value",
        type: "number",
        placeholder: "0",
        defaultValue: "",
        colSpan: 12,
      },
    ],
  },

  contacts: {
    title: "Contact",
    endpoint: "/api/contacts",

    filterKey: "status",
    filter: ["Active", "Inactive", "Blocked"],

    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "phone",
        label: "Phone",
        type: "tel",
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "company",
        label: "Company",
        type: "text",
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "designation",
        label: "Designation",
        type: "text",
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        defaultValue: "Active",
        colSpan: 6,
        options: ["Active", "Inactive", "Blocked"],
      },
    ],
  },

  activities: {
    title: "Activity",
    endpoint: "/api/activity",
    filterKey: "outcome",
    filter: ["Interested", "Replied", "Positive", "Negative"],

    fields: [
      {
        name: "type",
        label: "Type",
        type: "select",
        defaultValue: "",
        colSpan: 6,
        options: ["Email", "Call", "Meeting"],
      },
      {
        name: "outcome",
        label: "Outcome",
        type: "select",
        defaultValue: "",
        colSpan: 6,
        options: ["Interested", "Replied", "Positive", "Negative"],
      },
      {
        name: "notes",
        label: "Notes",
        type: "textarea",
        defaultValue: "",
        colSpan: 12,
      },
    ],
  },

  appointments: {
    title: "Appointment",
    endpoint: "/api/appointments",

    filterKey: "status",
    filter: ["Scheduled", "Completed"],

    fields: [
      {
        name: "title",
        label: "Title",
        type: "text",
        required: true,
        defaultValue: "",
        colSpan: 12,
      },
      {
        name: "description",
        label: "Description",
        type: "textarea",
        defaultValue: "",
        colSpan: 12,
      },
      {
        name: "start_time",
        label: "Start Time",
        type: "datetime-local",
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "end_time",
        label: "End Time",
        type: "datetime-local",
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "location",
        label: "Location",
        type: "select",
        defaultValue: "",
        colSpan: 6,
        options: ["Zoom Meeting", "Google Meet", "Client Office"],
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        defaultValue: "Scheduled",
        colSpan: 6,
        options: ["Scheduled", "Completed"],
      },
    ],
  },

  users: {
    title: "User",
    endpoint: "/api/users",

    filterKey: "status",
    filter: ["Active", "Inactive"],

    fields: [
      {
        name: "name",
        label: "Name",
        type: "text",
        required: true,
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "email",
        label: "Email",
        type: "email",
        required: true,
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "password",
        label: "Password",
        type: "password",
        required: true,
        defaultValue: "",
        colSpan: 12,
      },
      {
        name: "phone",
        label: "Phone",
        type: "text",
        defaultValue: "",
        colSpan: 6,
      },
      {
        name: "role",
        label: "Role",
        type: "select",
        defaultValue: "",
        colSpan: 6,
        options: [
          "Admin",
          "Accountant",
          "Finance",
          "HR Manager",
          "Support Manager",
          "Sales Executive",
          "Super Admin",
          "Support Agent",
          "Marketing Manager",
        ],
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        defaultValue: "Active",
        colSpan: 6,
        options: ["Active", "Inactive"],
      },
      {
        name: "access",
        label: "Module Access",
        type: "checkbox",
        defaultValue: [],
        options: [
          { label: "Dashboard", value: "dashboard" },
          { label: "Leads", value: "leads" },
          { label: "Contacts", value: "contacts" },
          { label: "Activities", value: "activities" },
          { label: "Appointments", value: "appointments" },
          { label: "Users", value: "users" },
        ],
      },
    ],
  },
};